import streamlit as st

def show_intro():
    col1,col2,col3 = st.columns(3)
    with col2:
        st.title("$FinComplyAI$")
        
    st.title("_About Us_")
    st.info("FinComplyAI™ can be described as an advanced financial analytics tool that leverages the power of artificial intelligence to analyze financial transactions for anti-money laundering (AML) purposes. The software works by taking a dataset of financial transactions, which is first processed through a web application that allows users to modify and customize the dataset according to specific parameters. This tailored dataset is then analyzed by a proprietary AI algorithm, which uses the OpenAI GPT model to interpret the data and assess it for potential AML risks, red flags, and other irregularities.")
    st.error("The AI analyzes the overall transactional activity, breaking it down into various categories and sub-categories, evaluating the reasonableness of high-risk transactions against the nature of the client's business, and assessing counterparty risk. This not only includes an analysis of the transactions themselves but also a comprehensive counterparty analysis, which assesses the risk associated with each counterparty involved in the transactions.")
    st.info("The software then generates a detailed report, which includes an analysis of the AML risks, red flags, recommendations for further investigation, and a counterparty analysis. This report is presented in a user-friendly template that can be easily understood and acted upon by bank employees, compliance officers, and other financial professionals that are required to identify AML risks.")
    st.error("One of the unique features of the software is its ability to allow users to provide nature of business and customize the analysis by selecting specific counterparties samples for AI evaluation. This is achieved through a feature in the web application that allows users to select the sampled counterparties variety (large, medium, small transactions), top 5, top 10, top 5%, or top 10% for analysis.")
    st.info("The software provides a comprehensive, customizable, and user-friendly solution for bank investigators and compliance professionals as the software provides a nearly instant output of overall activity and AI risk analysis helping investigations comply with regulatory requirements and protect their institutions from financial crime. The use of AI and machine learning algorithms ensures a high level of accuracy and efficiency in the analysis, while the web application interface ensures it is accessible and usable for financial professionals.")
